### ISSUE TITLE
allowed$ inconsistent with expected behavior

### ISSUE THREAD

**Issue by artfuldev** [artfuldev/recall-cycle#12]
When you keep creating new games, allowed$ still responds to the first puzzle$'s delayed allow setting

**Comment by Hypnosphi** [comment]
it can be something like

``` js
const allowed$ =
    puzzle$
        // emits true after 4 seconds, and false immediately
        .mapTo(xs.of(true).compose(delay(4000)).startWith(false))
        // cancels scheduled true value
        .flatten()
        .remember();
```

**Comment by artfuldev** [comment]
Actually this doesn't work as expected, can't figure out why. My inferior solution with periodic and distinctBooleans works. See the PR/commit.

**Comment by Hypnosphi** [comment]
Oh, I use `mapTo` here illegally. It should be `map(() => ...)`, because the internal stream should be created each time, not just once

**Comment by artfuldev** [comment]
Good catch!
