### ISSUE TITLE
Use Set for selected cells

### ISSUE THREAD

**Issue by Hypnosphi** [artfuldev/recall-cycle#9]
this would change

``` js
var selected = selectedCells.indexOf(clicked) !== -1;
            return selected
              ? selectedCells.filter(x => x != clicked)
              : selectedCells.concat(clicked);
```

to

``` js
return selectedCells.has(x)
              ? selectedCells.remove(x)
              : selectedCells.add(x);
```

**Comment by artfuldev** [comment]
Does add, remove work on a simple JS array?

**Comment by artfuldev** [comment]
LOL you want me to use a Set instead of an Array. Sorry, got confused.

**Comment by artfuldev** [comment]
But @Hypnosphi I don't want to mutate the property. `Set.add` mutates the set, doesn't it?

**Comment by artfuldev** [comment]
You want me to use Set from ImmutableJS? Currently I don't use ImmutableJS at all.

**Comment by artfuldev** [comment]
Do you think I can get away with introducing these `add`, `remove`, and `has` methods in a separate `utils.ts`?

**Comment by Hypnosphi** [comment]
If you want immutability, use Immutable.Set, yes

**Comment by Hypnosphi** [comment]
> Do you think I can get away with introducing these add, remove, and has methods in a separate utils.ts?

It may work, too. Maybe you can even imlement a `toggle` function for this behaviour
